send a message

diff --git a/.github/workflows/playwright.yml b/.github/workflows/playwright.yml
--- a/.github/workflows/playwright.yml
+++ b/.github/workflows/playwright.yml
@@ -12,36 +12,32 @@ on:
   schedule:
     - cron: '30 08 * * 0,1,2,3,4,5'
   workflow_dispatch:
-      inputs:
-        reporter:
-          required: false
-          description: 'Select a reporter'
-          type: choice
-          options:
-            - allure-playwright
-            - html
-            - blob
-            - list
-          default: allure-playwright
-        path-to-results:
-          required: false
-          description: 'Provide path to reporter files'
-          default: allure-results
-          type: choice
-          options:
-            - test-results/
-            - tests/playwright/blob-report
-            - allure-results
-        fail_fast:
-            type: boolean
-            required: true
-            description: 'Cancel tests when one of them fails'
-            default: false
-        tag:
-          description: 'Provide @tag or a keyword'
-          required: false
+    inputs:
+      reporter:
+        required: false
+        description: 'Select a reporter'
+        type: choice
+        options:
+          - allure-playwright
+          - html
+          - blob
+          - list
+        default: allure-playwright
+      path-to-results:
+        required: false
+        description: 'Provide path to reporter files'
+        default: allure-results
+        type: choice
+        options:
+          - test-results/
+          - tests/playwright/blob-report
+          - allure-results
+      fail_fast:
+        type: boolean
+        required: true
+        description: 'Cancel tests when one of them fails'
+        default: false
 
-# This allows a subsequently queued workflow run to interrupt previous runs
 concurrency:
   group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
   cancel-in-progress: true
@@ -50,26 +46,27 @@ jobs:
   build-plugin:
     name: Build plugin
     uses: ./.github/workflows/build.yml
+
   Playwright:
     name: Playwright test - ${{ matrix.shardIndex }} on PHP 8.0
     runs-on: ubuntu-latest
     needs: [build-plugin]
-    if: ${{ ( github.event.pull_request.title == null || needs.build-plugin.outputs.changelog_diff ) && github.event.inputs.tag == '' }}
+    if: ${{ github.event.pull_request.title == null || needs.build-plugin.outputs.changelog_diff }}
     strategy:
       fail-fast: ${{ inputs.fail_fast || false }}
       matrix:
-        shardIndex: [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 ]
-        shardTotal: [ 10 ]
-        include:
-        - shardIndex: "elements-regression"
+        shardIndex: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, "elements-regression", "known-issues"]
+        shardTotal: [10]
     steps:
       - name: Checkout source code
         uses: actions/checkout@v4
+
       - name: Install Node.js 20.x
         uses: actions/setup-node@v4
         with:
           node-version: 20.x
           cache: 'npm'
+
       - name: Install dependencies
         run: |
           npm ci
@@ -79,19 +76,23 @@ jobs:
         with:
           name: ${{ needs.build-plugin.outputs.artifact_name }}
           path: ./build
+
       - name: Update wp-env.json file
         env:
           PHP_VERSION: '8.0'
           WP_CORE_VERSION: 'latest'
         run: node ./.github/scripts/build-wp-env.js
+
       - name: Install WordPress environment
-        run: |
-          npm run start-local-server
-      - name: Update wordpress to nightly build
+        run: npm run start-local-server
+
+      - name: Update WordPress to nightly build
         if: ${{ github.event_name == 'schedule' }}
         run: npx wp-env run cli wp core update https://wordpress.org/nightly-builds/wordpress-latest.zip
+
       - name: Setup test data
         run: npm run test:setup:playwright
+
       - name: WordPress debug information
         run: |
           npx wp-env run cli wp core version
@@ -100,99 +101,87 @@ jobs:
         run: |
           npx playwright install chromium
       - name: Run Playwright tests
-        if: ${{ matrix.shardIndex != 'elements-regression' }}
-        run: npm run test:playwright  -- --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }} --reporter=${{ inputs.reporter || 'list,github' }}
+        if: ${{ matrix.shardIndex != 'elements-regression' && matrix.shardIndex != 'known-issues' }}
+        run: npm run test:playwright -- --grep-invert="@known-issue" --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }} --reporter=${{ inputs.reporter || 'list,github' }}
+
       - name: Run element regression tests
         if: ${{ matrix.shardIndex == 'elements-regression' }}
         run: npm run test:playwright:elements-regression -- --reporter=${{ inputs.reporter || 'list,github' }}
-      - uses: actions/upload-artifact@v4
-        if: always()
-        with:
-          name: playwright-test-results-${{ matrix.shardIndex }}
-          path: ${{ inputs.path-to-results || 'test-results/' }}
-          if-no-files-found: ignore
-          retention-days: 2
-  PlaywrightWithTag:
-    name: Playwright test - tagged tests on PHP 8.0
-    runs-on: ubuntu-latest
-    needs: [ build-plugin ]
-    if: ${{ github.event.inputs.tag }}
-    steps:
-      - name: Checkout source code
-        uses: actions/checkout@v4
-      - name: Install Node.js 20.x
-        uses: actions/setup-node@v4
-        with:
-          node-version: 20.x
-          cache: 'npm'
-      - name: Install dependencies
-        run: |
-          npm ci
-          sed -i -e "s/image: 'mariadb:lts'/image: 'mariadb:11.2.4-jammy'/g" node_modules/@wordpress/env/lib/build-docker-compose-config.js
-      - name: Download build artifact
-        uses: actions/download-artifact@v4
-        with:
-          name: ${{ needs.build-plugin.outputs.artifact_name }}
-          path: ./build
-      - name: Update wp-env.json file
-        env:
-          PHP_VERSION: '8.0'
-          WP_CORE_VERSION: 'latest'
-        run: node ./.github/scripts/build-wp-env.js
-      - name: Install WordPress environment
-        run: |
-          npm run start-local-server
-      - name: Setup test data
-        run: npm run test:setup:playwright
-      - name: WordPress debug information
-        run: |
-          npx wp-env run cli wp core version
-          npx wp-env run cli wp --info
-      - name: Install playwright/test
-        run: |
-          npx playwright install chromium
-      - name: Run Playwright tests
-        run: |
-          npm run test:playwright -- --grep="${{ inputs.tag }}" --reporter=list,allure-playwright
-      - uses: actions/upload-artifact@v4
-        if: always()
-        with:
-          name: playwright-test-results-tagged-tests
-          path: ${{ inputs.path-to-results || 'test-results/' }}
-          if-no-files-found: ignore
-          retention-days: 2
 
+      - name: Run tests with known issues
+        if: ${{ matrix.shardIndex == 'known-issues' }}
+        run: |
+          # Run Playwright tests for known issues
+          echo "Running tests with '@known-issue' tag..."
+          npm run test:playwright -- --grep="@known-issue" --reporter=${{ inputs.reporter || 'list,github' }}
+          # Capture test status
+          TEST_EXIT_CODE=$?
+          # Ensure known-issues-status.txt is created
+          echo "Known issues test run completed." > known-issues-status.txt
+          if [ $TEST_EXIT_CODE -ne 0 ]; then
+            echo "Test Result: Failed" >> known-issues-status.txt
+          else
+            echo "Test Result: Passed" >> known-issues-status.txt
+          fi
+          exit $TEST_EXIT_CODE
+      - name: Debug artifact existence
+        if: ${{ matrix.shardIndex == 'known-issues' }}
+        run: |
+          echo "Debugging known-issues-status.txt existence..."
+          ls -la
+          cat known-issues-status.txt || echo "File does not exist!"
+      - name: Upload known issues status
+        if: ${{ matrix.shardIndex == 'known-issues' }}
+        uses: actions/upload-artifact@v4
+        with:
+          name: known-issues
+          path: known-issues-status.txt
 
   test-result:
     needs: Playwright
-    if: ${{ always() }} # Will be run even if 'Playwright' matrix will be skipped
+    if: ${{ always() }}
     runs-on: ubuntu-22.04
     name: Playwright - Test Results
     steps:
       - name: Test status
         run: echo "Test status is - ${{ needs.Playwright.result }}"
+
+      - name: Download known issues status
+        uses: actions/download-artifact@v4
+        with:
+          name: known-issues
+
+      - name: Check known issues file existence
+        id: check-known-issues
+        run: |
+          if [ -f known-issues-status.txt ]; then
+            echo "file_exists=true" >> $GITHUB_ENV
+          else
+            echo "file_exists=false" >> $GITHUB_ENV
+          fi
+      - name: Debug downloaded artifact
+        run: |
+          echo "Downloaded artifact contents:"
+          cat known-issues-status.txt || echo "File not found!"
       - name: Checkout source code
-        if: ${{ needs.Playwright.result == 'failure' && github.event_name == 'schedule' }}
+        if: ${{ always() }}
         uses: actions/checkout@v4
-      - name: Send slack message
-        if: ${{ needs.Playwright.result == 'failure' && github.event_name == 'schedule' }}
+      - name: Send Slack message for known issues
+        if: env.file_exists == 'true'
         uses: ./.github/workflows/post-to-slack
         with:
           SLACK_BOT_TOKEN: ${{ secrets.SLACK_TOKEN }}
           SLACK_TAG_CHANNELS: ${{ secrets.TEST_AUTOMATION_RESULTS }}
           PAYLOAD: |
             {
-              "text": "Elementor Core: Playwright with WordPress nightly has failed: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
+              "text": "Elementor Core: Known issues test failed: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
               "blocks": [
                 {
                   "type": "section",
                   "text": {
                     "type": "mrkdwn",
-                    "text": "Elementor Core: Playwright with WordPress nightly failed: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
+                    "text": "Elementor Core: Known issues test failed: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                   }
                 }
               ]
             }
-      - name: Check Playwright matrix status
-        if: ${{ needs.Playwright.result != 'success' && needs.Playwright.result != 'skipped' }}
-        run: exit 1
